/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2labp2_michaelmartinez;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael Martínez
 * 
 * //Filo 2 Asiento 8
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registarAuto = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jb_crearCarroNuevo = new javax.swing.JButton();
        tf_marca = new javax.swing.JTextField();
        tf_modelo = new javax.swing.JTextField();
        js_velocidad = new javax.swing.JSpinner();
        jd_carrera = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        tiempo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jl_carro1 = new javax.swing.JLabel();
        jl_carro2 = new javax.swing.JLabel();
        pb_barra1 = new javax.swing.JProgressBar();
        pb_barra2 = new javax.swing.JProgressBar();
        jb_IniciarCarrera = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_carro1 = new javax.swing.JComboBox<>();
        cb_carro2 = new javax.swing.JComboBox<>();
        jb_crearCarro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jl_marca = new javax.swing.JLabel();
        jl_marca2 = new javax.swing.JLabel();
        jl_modelo = new javax.swing.JLabel();
        jl_modelo2 = new javax.swing.JLabel();
        jl_velocidad = new javax.swing.JLabel();
        jl_velocidad2 = new javax.swing.JLabel();
        jb_refresh = new javax.swing.JButton();
        jb_iniciarVS = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("CREACIÓN DE CARROS");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("MARCA");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("MODELO");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("VELOCIDAD");

        jb_crearCarroNuevo.setText("CREAR");
        jb_crearCarroNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearCarroNuevoMouseClicked(evt);
            }
        });

        tf_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_modeloActionPerformed(evt);
            }
        });

        js_velocidad.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout jd_registarAutoLayout = new javax.swing.GroupLayout(jd_registarAuto.getContentPane());
        jd_registarAuto.getContentPane().setLayout(jd_registarAutoLayout);
        jd_registarAutoLayout.setHorizontalGroup(
            jd_registarAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registarAutoLayout.createSequentialGroup()
                .addGroup(jd_registarAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_registarAutoLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel11))
                    .addGroup(jd_registarAutoLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_registarAutoLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel12))
                    .addGroup(jd_registarAutoLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jd_registarAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_marca)
                            .addComponent(tf_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registarAutoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jd_registarAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registarAutoLayout.createSequentialGroup()
                        .addComponent(jb_crearCarroNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registarAutoLayout.createSequentialGroup()
                        .addGroup(jd_registarAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(js_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(199, 199, 199))))
        );
        jd_registarAutoLayout.setVerticalGroup(
            jd_registarAutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registarAutoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(7, 7, 7)
                .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(5, 5, 5)
                .addComponent(tf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(js_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jb_crearCarroNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("TIEMPO");

        tiempo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("PROGRESO");

        pb_barra1.setMaximum(150);

        pb_barra2.setMaximum(150);

        jb_IniciarCarrera.setText("INICIAR");
        jb_IniciarCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_IniciarCarreraMouseClicked(evt);
            }
        });

        jLabel17.setText("CARRO 1");

        jLabel18.setText("CARRO 2");

        javax.swing.GroupLayout jd_carreraLayout = new javax.swing.GroupLayout(jd_carrera.getContentPane());
        jd_carrera.getContentPane().setLayout(jd_carreraLayout);
        jd_carreraLayout.setHorizontalGroup(
            jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_carreraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pb_barra2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(pb_barra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(202, 202, 202))
            .addGroup(jd_carreraLayout.createSequentialGroup()
                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_carreraLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jb_IniciarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_carreraLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(tiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jd_carreraLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_carreraLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jl_carro2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_carreraLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_carro1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jd_carreraLayout.setVerticalGroup(
            jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_carreraLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_carreraLayout.createSequentialGroup()
                        .addComponent(jl_carro1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_carreraLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(30, 30, 30)))
                .addComponent(pb_barra1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_carreraLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jl_carro2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_carreraLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel18)))
                .addGap(28, 28, 28)
                .addComponent(pb_barra2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jb_IniciarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("P A R T  I D A ");

        jLabel2.setText("Jugador 1");

        jLabel3.setText("Jugador 2");

        cb_carro1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_carro1ItemStateChanged(evt);
            }
        });

        cb_carro2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_carro2ItemStateChanged(evt);
            }
        });

        jb_crearCarro.setText("Crear Carro");
        jb_crearCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearCarroMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("MARCA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("MARCA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("MODELO");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("MODELO");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("VELOCIDAD");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("VELOCIDAD");

        jb_refresh.setText("Actualizar ComboBox");
        jb_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_refreshMouseClicked(evt);
            }
        });

        jb_iniciarVS.setText("INICIAR");
        jb_iniciarVS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_iniciarVSMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("VS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jl_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jl_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jl_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8))
                                                .addGap(75, 75, 75)
                                                .addComponent(jb_iniciarVS, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jb_refresh)))
                                        .addGap(24, 24, 24)))))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cb_carro1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_crearCarro)
                    .addComponent(cb_carro2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_velocidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jl_marca2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addComponent(jl_modelo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_crearCarro)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_carro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_carro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jb_refresh)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_marca2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jl_marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_modelo2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jl_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jl_velocidad2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jl_velocidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jb_iniciarVS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearCarroMouseClicked
        // TODO add your handling code here:
        jd_registarAuto.pack();
        jd_registarAuto.setLocationRelativeTo(this);
        jd_registarAuto.setModal(true);
        jd_registarAuto.setVisible(true);
        
                
    }//GEN-LAST:event_jb_crearCarroMouseClicked

    private void jb_crearCarroNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearCarroNuevoMouseClicked
        try {
            // TODO add your handling code here:
            AdminCarros admin=new AdminCarros("./ListaCarros.tn");
            admin.leer();
            if (tf_marca.getText().equals("")|| tf_modelo.getText().equals("")) {
                JOptionPane.showMessageDialog(jd_registarAuto, "Hay un campo vacío");
            } else {
                Carro carroNuevo = new Carro(tf_marca.getText(), tf_modelo.getText(), Integer.parseInt(js_velocidad.getValue() + ""));
                admin.getListaCarros().add(carroNuevo);
                JOptionPane.showMessageDialog(jd_registarAuto, "Carro creado exitosamente");
                admin.escribir();
                tf_marca.setText("");
                tf_modelo.setText("");
                js_velocidad.setValue(0);
            }
            
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jb_crearCarroNuevoMouseClicked

    private void cb_carro1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_carro1ItemStateChanged
        // TODO add your handling code here:
        
        DefaultComboBoxModel modelo=(DefaultComboBoxModel)cb_carro1.getModel();
        Carro carro=(Carro) modelo.getElementAt(cb_carro1.getSelectedIndex());
        jl_marca.setText(carro.getMarca());
        jl_modelo.setText(carro.getModelo());
        jl_velocidad.setText(carro.getVelocidad()+"");
    }//GEN-LAST:event_cb_carro1ItemStateChanged

    private void cb_carro2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_carro2ItemStateChanged
        // TODO add your handling code here:
        
        DefaultComboBoxModel modelo=(DefaultComboBoxModel)cb_carro2.getModel();
        Carro carro=(Carro) modelo.getElementAt(cb_carro2.getSelectedIndex());
        jl_marca2.setText(carro.getMarca());
        jl_modelo2.setText(carro.getModelo());
        jl_velocidad2.setText(carro.getVelocidad()+"");
    }//GEN-LAST:event_cb_carro2ItemStateChanged

    private void tf_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_modeloActionPerformed

    private void jb_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_refreshMouseClicked
        // TODO add your handling code here:
        AdminCarros admin=new AdminCarros("./ListaCarros.tn");
        admin.leer();
        //modelos de comboBox
        DefaultComboBoxModel modelo1=(DefaultComboBoxModel)cb_carro1.getModel();
        DefaultComboBoxModel modelo2=(DefaultComboBoxModel)cb_carro2.getModel();
        modelo1.removeAllElements();
        modelo2.removeAllElements();
        for (int i = 0; i < admin.getListaCarros().size(); i++) {
            modelo1.addElement(admin.getListaCarros().get(i));
            modelo2.addElement(admin.getListaCarros().get(i));
        }
        cb_carro1.setModel(modelo1);
        cb_carro2.setModel(modelo2);
    }//GEN-LAST:event_jb_refreshMouseClicked

    private void jb_iniciarVSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_iniciarVSMouseClicked
        // TODO add your handling code here:
        jl_carro1.setText("");
        jl_carro2.setText("");
        tiempo.setText("");
        pb_barra1.setValue(0);
        pb_barra2.setValue(0);
        DefaultComboBoxModel modelo1=(DefaultComboBoxModel)cb_carro1.getModel();
        DefaultComboBoxModel modelo2=(DefaultComboBoxModel)cb_carro2.getModel();
        carro1=(Carro) modelo1.getElementAt(cb_carro1.getSelectedIndex());
        carro2=(Carro) modelo2.getElementAt(cb_carro2.getSelectedIndex());
        jl_carro1.setText(carro1.getModelo());
        jl_carro2.setText(carro2.getModelo());
        jd_carrera.pack();
        jd_carrera.setLocationRelativeTo(this);
        jd_carrera.setModal(true);
        jd_carrera.setVisible(true);
        
        //carrosSelected
       
    }//GEN-LAST:event_jb_iniciarVSMouseClicked

    private void jb_IniciarCarreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_IniciarCarreraMouseClicked
        // TODO add your handling code here:
        //Iniciar Hilos
        DefaultComboBoxModel modelo1=(DefaultComboBoxModel)cb_carro1.getModel();
        DefaultComboBoxModel modelo2=(DefaultComboBoxModel)cb_carro2.getModel();
        carro1=(Carro) modelo1.getElementAt(cb_carro1.getSelectedIndex());
        carro2=(Carro) modelo2.getElementAt(cb_carro2.getSelectedIndex());
        hiloPrimerCarro hilo=new hiloPrimerCarro(pb_barra1, carro1.getVelocidad(), pb_barra2, carro2.getVelocidad(), "",tiempo);
        Thread proceso=new Thread(hilo);
        proceso.start();
       
    }//GEN-LAST:event_jb_IniciarCarreraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
Carro carro1;
Carro carro2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_carro1;
    private javax.swing.JComboBox<String> cb_carro2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jb_IniciarCarrera;
    private javax.swing.JButton jb_crearCarro;
    private javax.swing.JButton jb_crearCarroNuevo;
    private javax.swing.JButton jb_iniciarVS;
    private javax.swing.JButton jb_refresh;
    private javax.swing.JDialog jd_carrera;
    private javax.swing.JDialog jd_registarAuto;
    private javax.swing.JLabel jl_carro1;
    private javax.swing.JLabel jl_carro2;
    private javax.swing.JLabel jl_marca;
    private javax.swing.JLabel jl_marca2;
    private javax.swing.JLabel jl_modelo;
    private javax.swing.JLabel jl_modelo2;
    private javax.swing.JLabel jl_velocidad;
    private javax.swing.JLabel jl_velocidad2;
    private javax.swing.JSpinner js_velocidad;
    private javax.swing.JProgressBar pb_barra1;
    private javax.swing.JProgressBar pb_barra2;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_modelo;
    private javax.swing.JLabel tiempo;
    // End of variables declaration//GEN-END:variables
}
